---
format: 
  pdf: 
    documentclass: article
    papersize: A4
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---
<!-- TITLE -->
\begin{huge}\begin{center}{\bf Andrew Hayden Morris}\end{center}\end{huge}

<!-- CONTACT INFO -->
\begin{center}andrewmorris@mailbox.org ∙ \href{https://ahmorris.org}{Personlig Nettside} ∙ \href{https://github.com/amorris28}{Github} ∙ \href{https://www.linkedin.com/in/ahmorris/}{LinkedIn}
\end{center}
<!-- \begin{center}Located in Oslo, Norway -->
<!-- \end{center} -->
\vspace{5pt}



<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf UTDANNING}
  \vspace{3pt}
  \hrule
  \vspace{10pt}
  
  {\bf Doktorgrad i biologi}, (2022) {\it University of Oregon} \hfill Eugene, OR, USA
  
\end{large}

<!-- \vspace{5pt} -->

<!-- EDUCATION: 2ND BULLET -->
\begin{large}
{\bf Mastergrad i jordvitenskap}, (2017) {\it The Pennsylvania State University} \hfill State College, PA, USA
    
\end{large}

<!-- \vspace{5pt} -->

<!-- EDUCATION: 3RD BULLET -->
\begin{large}

{\bf Bachelor i plantevitenskap}, (2014) {\it Cornell University} \hfill Ithaca, NY, USA

\end{large}

\vspace{25pt}

<!--EXPERIENCE : 1ST BULLET -->

\begin{large}{\bf RELEVANT ERFARING}

  \vspace{3pt}
  \hrule
  \vspace{10pt}
  {\bf Postdoktor i big data og presisjonsmedisin}
  \hfill 03.24 - d.d.

  \vspace{-0.17cm}

  Senter for presisjonspsykiatri, Universitet i Oslo
  \hfill Oslo, Norge
  
\end{large}
\parbox{400pt}{
  \begin{itemize}
 \item Analyzed large-scale datasets from Norwegian health registries combining genetic data with electronic health records to model age of onset for disease across tens of thousands of subjects
 \item Developed clear visualizations and statistical models for individualized risk prediction
 \item Collaborated with domain experts in oncology, genetics, and epidemiology to define hypotheses and develop statistical analyses
 \item Supported the development of a precision medicine platform to be integrated into the Norwegian healthcare system
\end{itemize}
}

\vspace{15pt}

<!-- EXPERIENCE : 2ND BULLET-->

\begin{large}
  
  {\bf Postdoktor i dyremikrobiomer og akvakultursystemer}
  \hfill 03.22 - 12.23
  \vspace{-0.17cm}

  Institute of Ecology and Evolution, University of Oregon
  \hfill Eugene, OR, USA

  Institutt for bioteknologi og matvitenskap, NTNU
  \hfill Trondheim, Norge
\end{large}

\parbox{400pt}{
  \begin{itemize}
\item Analyzed aquaculture datasets investigating the impact of environmental factors (antibiotic treatment, stocking density) on fish health and growth outcomes
\item Conducted comparative analysis of recirculating aquaculture systems between Oregon and Norwegian facilities, established data collection protocols for water quality and fish health monitoring
\item Conducted meta-analysis of 50+ unstructured datasets from published reports on animal microbiomes and presented findings in \textit{Nature Microbiology}
\item Collaborated with international teams of biologists, aquaculture experts, and data scientists to translate research questions into analytical approaches
\end{itemize}
}

\vspace{15pt}


<!-- EXPERIENCE : 3RD BULLET-->

\begin{large}
  {\bf Ph.d.-stipendiat} \hfill 08.17 - 03.22

  \vspace{-0.17cm}

  Institute of Ecology and Evolution, University of Oregon \hfill Eugene, OR, USA

\end{large}

\parbox{400pt}{
  \begin{itemize}
\item Analyzed environmental datasets from dozens of field sites across Brazil and Gabon, identifying patterns in soil characteristics and greenhouse gas emissions
\item Developed statistical models integrating laboratory experiments with field observations
\item Uncovered insights that contributed to \$3 million USD in funding from the U.S. National Science Foundation
\item Collaborated with interdisciplinary teams of ecologists, microbiologists, and soil scientists in Brazil, Gabon, and the US
\end{itemize}
}

\vspace{15pt}

<!-- EXPERIENCE : 5TH BULLET-->

\begin{large}

  {\bf M.S.-stipendiat} \hfill 08.15 - 07.17

  \vspace{-0.17cm}
  
  Department of Ecosystem Science and Management, 
  Penn State University
  \hfill State College, PA, USA
  
\end{large}

\parbox{400pt}{
  \begin{itemize}
\item Collaborated with agricultural industry partners to design and implement experiments at research stations and on commercial farms
\item Developed statistical models to understand the relationship between on-farm practices and environmental impacts through nutrient pollution and greenhouse gas emissions
\item Presented data-driven recommendations to farmers, industry partners, and extension agents to facilitate informed decision making
\end{itemize}
}


{{< pagebreak >}}

<!-- SKILLS -->
\begin{large}{\bf TEKNISKE FERDIGHETER}
  \vspace{3pt}
  \hrule
  \vspace{10pt}
\end{large}

**Statistisk analyse og programmering**

 * **R** - Ekspertnivå: statistisk modellering, datamanipulering, datavisualisering (ggplot2) og pakkeutvikling
 * **Python** - Intermediate: Proficient in data processing, statistical analysis and scripting
 * **SQL** - Basic proficiency in queries, syntax and database concepts; extensive experience with equivalent data manipulation in R (dplyr)
 * **Statistical Methods** - Extensive experience with regression modeling, mixed-effects models, multivariate analysis, and experimental design

  \vspace{10pt}
 
**Datavisualisering og kommunikasjon**

 * **Visualization** - Advanced skills with ggplot2, creating publication-quality graphics and interactive plots
 * **Data Storytelling** - Experienced in translating complex statistical findings for diverse audiences
 * **Technical Writing** - Skilled in documenting analytical methods and presenting results in scientific publications

  \vspace{10pt}
 
**Datateknikk og samarkbeid**

 * **Version Control** -  Experienced with Git and GitHub for collaborative analysis projects
 * **Cloud Platforms** - Experienced with high-performance computing environments (Slurm, Tjenester for Sensitive Data)
 * **Unix/Bash** - Proficient in command-line tools and shell scripting for automation

\vspace{30pt}

<!-- LANGUAGES -->
\begin{large}
{\bf SPRÅK}
  \vspace{3pt}
  \hrule
  \vspace{10pt}
  
\end{large}

**Engelsk**: Morsmål. Utmerket skriftlig og muntlig.

**Norsk**: Fullførte kurs i A1/A2. Selvstudium i B1/B2.




<!-- **Selected Coursework** -->

<!-- * Genome-Wide Association Studies -->
<!-- * Machine Learning for Image Analysis -->
<!-- * Strategies and Techniques for Analyzing Microbial Community Population Structures -->
<!-- * Advanced Biological Statistics I \& II -->

\vspace{30pt}

<!-- REFERENCES -->
<!--
\begin{large}
{\bf REFERENCES}
  \vspace{3pt}
  \hrule
  \vspace{10pt}
    
  \vspace{-0.17cm}
\end{large}

 * Oleksandr Frei, Researcher, University of Oslo, oleksandr.frei@medisin.uio.no Tel: +47 417 94 331
 * Prof. Brendan Bohannan, University of Oregon, bohannan@uoregon.edu Tel: +1 541 346 4883
 * Prof. Jason Kaye, Penn State University, jpk12@psu.edu Tel: +1 814 863 1614
-->
